### ISSUE TITLE
Sticker Wm

### ISSUE THREAD

**Issue by ZefianAlfian** [Zobin33/Zbin-Wabot#3]
https://github.com/Zobin33/Anu-Wabot/blob/main/plugins/swm.js

Itu bisa dipake bang? cara pakenya gimana

**Comment by GynnnDev** [comment]
Gatau Jir Bukan Punya Gw Ntar Gw Bikin Example, Gw lagi Males:v

**Comment by GynnnDev** [comment]
Kemana ae jir gw nyari:v
